<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\User;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->truncate();
        $data = [
            [
                'id' => '1',
                'name' => 'Superadmin',
                'email' => 'superadmin@app.com',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '2',
                'name' => 'Admin BPBD',
                'opd_tp' => 'OPD_TP_01',
                'email' => 'bpbdkabwsb@gmail.com',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '3',
                'name' => 'SYAEFUL UMAM, S.Pd',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_01',
                'alamat' => 'Campursari 03/01 Selomerto, Selomerto',
                'nomor' => '085712001176',
                'email' => 'syaeful23umam@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_01',
                'tanggal_lahir' => '1993-03-23',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '4',
                'name' => 'YUNDAR IBNU FRENDIYANTORO, S.Pd',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_05',
                'alamat' => 'Plugon, 02/01 Donomulyo Nanggulan Kulon Progo',
                'nomor' => '085642088892',
                'email' => 'Yundaribnufrediyant@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_02',
                'tanggal_lahir' => '1992-06-07',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '5',
                'name' => 'WARDIYONO, SE',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_02',
                'alamat' => 'Perum. Purnamandala blockC 5 RT 04 RW 05 Bumireso Wonosobo',
                'nomor' => '082137377185',
                'email' => 'a082137377185@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_02',
                'tanggal_lahir' => '1982-03-14',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '6',
                'name' => 'INDAH KARTIKA CAHYANI,S.Sos',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_01',
                'alamat' => 'Dsn. Karangkobar 02/02 Kecis Selomerto, Wonosobo',
                'nomor' => '085229839145',
                'email' => 'indahkace@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_03',
                'tanggal_lahir' => '1994-04-19',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '7',
                'name' => 'RENI LESTARI, A.Md',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_02',
                'alamat' => 'Timbang 03/04 Leksono',
                'nomor' => '082242459402',
                'email' => 'renilestari094@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_03',
                'tanggal_lahir' => '1994-04-09',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '8',
                'name' => 'INDRA SURYANTAKA',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_03',
                'alamat' => 'Munggang Atas 01/12 Kalibeber Mojotengah',
                'nomor' => '081327671582',
                'email' => 'karindabilqis@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_02',
                'tanggal_lahir' => '1994-04-13',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '9',
                'name' => 'GRISELA FEBRIAWAN',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_04',
                'alamat' => 'Selokromo 02/06 Leksono',
                'nomor' => '082227755145',
                'email' => 'kurdncobain95@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_04',
                'tanggal_lahir' => '1989-02-22',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '10',
                'name' => 'RULIYANTO',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_05',
                'alamat' => 'Mekarsari 01/13 Kalibeber Mojotengah',
                'nomor' => '082242490970',
                'email' => 'ruliyantoruliyanto67@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_02',
                'tanggal_lahir' => '1987-10-17',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '11',
                'name' => 'FUAD HASAN',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_06',
                'alamat' => 'Jaraksari 03/01 Jaraksari Wonosobo',
                'nomor' => '081227263464',
                'email' => 'fuadh4466@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_02',
                'tanggal_lahir' => '1970-04-28',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '12',
                'name' => 'SUMEDI',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_07',
                'alamat' => 'Ngaglik 01/04 Pancurwening Wonosobo',
                'nomor' => '085700272307',
                'email' => 'istiqomahwonosobo83@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_02',
                'tanggal_lahir' => '1974-12-31',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '13',
                'name' => 'BUDI PURNOMO',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_08',
                'alamat' => 'Kaliputih 02/10 Tieng Kejajar',
                'nomor' => '081237808686',
                'email' => 'budip9592@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_01',
                'tanggal_lahir' => '1989-07-08',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '14',
                'name' => 'RIFKI ANIISA',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_09',
                'alamat' => 'Pungangan 11/01 Mojotengah',
                'nomor' => '085708477672',
                'email' => 'rifkianisa92@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_03',
                'tanggal_lahir' => '1992-10-30',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '15',
                'name' => 'PANGGUNG PRASETYO HADI',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_10',
                'alamat' => 'Campursari 03/01 Selomerto, Selomerto',
                'nomor' => '085708477672',
                'email' => 'panggungprasetyo@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_01',
                'tanggal_lahir' => '1999-05-01',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '16',
                'name' => 'MEILANA KURNIAWAN',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_11',
                'alamat' => 'Binangun, 9/5 Wiringanom',
                'nomor' => '085877120980',
                'email' => 'meilanakurniawan77@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_01',
                'tanggal_lahir' => '1991-05-23',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '17',
                'name' => 'SULIS',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_12',
                'alamat' => 'Sarimulyo, 5/2 Tawangsari Wonosobo',
                'nomor' => '089638468796',
                'email' => 'massulis349@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_01',
                'tanggal_lahir' => '1991-12-01',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '18',
                'name' => 'MAHRUN SAJIONO',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_13',
                'alamat' => 'Bowongso, 4/2 Kalikajar',
                'nomor' => '082325302876',
                'email' => 'mahrunsarjiono@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_01',
                'tanggal_lahir' => '1975-12-31',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '19',
                'name' => 'TURYONO MARKAM',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_14',
                'alamat' => 'Jaraksari 14/01 Jarakasi Wonosobo',
                'nomor' => '089528213146',
                'email' => 'pamansemar858@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_01',
                'tanggal_lahir' => '1979-11-07',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '20',
                'name' => 'ZAENAL AKROM ARIEZAL',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_03',
                'alamat' => 'Jaraksari 14/01 Jarakasi Wonosobo',
                'nomor' => '081225186129',
                'email' => 'zaenal.akrom70@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_01',
                'tanggal_lahir' => '1970-12-12',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '21',
                'name' => 'SABARNO',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_01',
                'alamat' => 'Dsn. Kapencar 03/09 Ds. Kapencar Kertek',
                'nomor' => '082226447611',
                'email' => 'bangjack445@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_01',
                'tanggal_lahir' => '1978-09-30',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '22',
                'name' => 'HARYADI',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_02',
                'alamat' => 'Munggang Atas 01/12 Kalibeber Mojotengah',
                'nomor' => '081353293464',
                'email' => 'aljesweweh@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_01',
                'tanggal_lahir' => '1998-03-02',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '23',
                'name' => 'BANGKIT ADI WIBOWO',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_03',
                'alamat' => 'Gunungtawang 4/1 Selomerto',
                'nomor' => '085236960623',
                'email' => 'bangkitadhi03@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_01',
                'tanggal_lahir' => '1995-03-08',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '24',
                'name' => 'WAHAB ABDILLAH',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_04',
                'alamat' => 'Munggang Bawah 3/11Kalibeber Mojotengah',
                'nomor' => '085879929955',
                'email' => 'sarteam040@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_01',
                'tanggal_lahir' => '1983-08-20',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ],
            [
                'id' => '25',
                'name' => 'TEGUH SURATNO',
                'tempat_lahir_tp' => 'TEMPAT_LAHIR_TP_04',
                'alamat' => 'Krajan 001/003 Larangankulon, Mojotengah',
                'nomor' => '085293936884',
                'email' => 'teguhsuratno3@gmail.com',
                'jabatan_tp' => 'JABATAN_TP_05',
                'tanggal_lahir' => '1985-09-21',
                'opd_tp' => 'OPD_TP_01',
                'password' => '$2y$10$iaFDvfu0za8ldbEnp/gmTu0zcRayGRWrZuBjP9G2XWo.b.WUcSdXO',
            ]
    
        ];

        foreach ($data as $datum) {
            User::create($datum);
        }
    }
}
